//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companhia
    {
        public Companhia()
        {
            this.Chegada = new HashSet<Chegada>();
            this.Balcaos = new HashSet<Balcao>();
            this.Partidas = new HashSet<Partida>();
        }
    
        public decimal Id { get; set; }
        public byte[] Icon { get; set; }
        public string Contacto { get; set; }
        public string Nome { get; set; }
        public string Sigla { get; set; }
    
        public virtual ICollection<Chegada> Chegada { get; set; }
        public virtual ICollection<Balcao> Balcaos { get; set; }
        public virtual ICollection<Partida> Partidas { get; set; }
    }
}
