//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        public decimal Id { get; set; }
        public Nullable<decimal> Companhia { get; set; }
        public string Voo { get; set; }
        public string Partida1 { get; set; }
        public string Previsao { get; set; }
        public string Obs { get; set; }
    
        public virtual Companhia Companhia1 { get; set; }
    }
}
